### ISSUE TITLE
Travis folding for knitr/bookdown

### ISSUE THREAD

**Issue by hadley** [tidyverse/dev-day-2019#14]
See https://github.com/yihui/knitr/issues/1654

**Comment by leonawicz** [comment]
I'd love to try this one for dev day but I'd need help getting started.

**Comment by cderv** [comment]
I think I know how to do that one. I'll try. 
Which is the TRAVIS env var to check for ? Just `Sys.getenv("TRAVIS")` ?

**Comment by hadley** [comment]
[Yup](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables)

**Comment by hadley** [comment]
Thanks @cderv! I'll close this issue since it's now being tracked elsewhere.

The impact isn't quite as great as I had hoped - it seems like the travis js processes the log file rather slowly.
