### ISSUE TITLE
An issue to keep track of work done in the cienciadedatos repo

### ISSUE THREAD

**Issue by raynamharris** [tidyverse/dev-day-2019#16]
The purpose of this issue is to track issues relaSpanish translation of R4DS that were worked on during the TidyVerse Developer Day

- [x] https://github.com/cienciadedatos/datos/issues/32
- [x] https://github.com/cienciadedatos/datos/issues/33 
- [x] https://github.com/cienciadedatos/datos/issues/34
- [ ] https://github.com/cienciadedatos/datos/issues/35
- [x] https://github.com/cienciadedatos/datos/issues/36
- [x] https://github.com/cienciadedatos/datos/issues/37
- [x] https://github.com/cienciadedatos/datos/issues/38
- [x] https://github.com/cienciadedatos/r4ds/issues/45
- [x] https://github.com/cienciadedatos/descripcion-y-orientaciones/issues/17

**Comment by pachamaltese** [comment]
@raynamharris d9e0c79 closes #33

**Comment by pachamaltese** [comment]
@raynamharris #37 is closed too

**Comment by jennybc** [comment]
I assume the primary tracking of this is elsewhere.
