### ISSUE TITLE
Post-mortem

### ISSUE THREAD

**Issue by jimhester** [tidyverse/dev-day-2019#17]
Not sure if we are collecting notes about the dev day, but I had a couple so I am putting them here.

**Comment by jennybc** [comment]
Emphasis **fork** then clone.

**Comment by hadley** [comment]
* styler for tidyverse style
* hopefully more sitrep functions for next time

**Comment by jennybc** [comment]
Play some background music? I did that during "your turn" segments in the WTF workshop and I thought it gave those segments a nice, warmer feeling. However, at dev day, there is plenty of background noise and people chatting already ...

**Comment by jennybc** [comment]
Definitive instructions about magic keywords:

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by hadley** [comment]
Another problem that hit a few people: assuming you can use any package in the tidyverse. Need to check what the package currently imports first.

**Comment by jennybc** [comment]
> Another problem that hit a few people: assuming you can use any package in the tidyverse. Need to check what the package currently imports first.

This would be easier to give advice for when we make progress on:

  * use_package should print recursive list of dependencies that will be added https://github.com/r-lib/usethis/issues/310
