### ISSUE TITLE
Start on readme

### ISSUE THREAD

**Issue by hadley** [tidyverse/dev-day-2019#3]
@batpigandme could you please just do a quick dump https://www.tidyverse.org/articles/2018/08/tidyverse-developer-day/ of into the readme ?

**Comment by hadley** [comment]
Also need to note:

* Code of conduct applies
* We're charging a nominal fee in order to get accurate count. All tickets will be donated to charity
* Link to ticket sales (https://www.eventbrite.com/e/tidyverse-developer-day-tickets-1617065687)

**Comment by batpigandme** [comment]
Copy that, about to head out, but I'll hit this tonight

**Comment by batpigandme** [comment]
This is all set but for the "list of planned tables," since I'm not sure we've confirmed those yet.
